// Profile: OpenMRSEncounter
// Parent: Encounter
// Id: OpenMRS-encounter
// Title: "OpenMRS Encounter"
// Description: "Encounter resource associated with the Service Request for a OpenMRS order generated by the FHIR2"
